package com.hsicen.aligntextview

import android.os.Bundle
import androidx.appcompat.app.AppCompatActivity
import kotlinx.android.synthetic.main.activity_main.*

class MainActivity : AppCompatActivity() {
    private val text1 =
        "是由一个网站获得，并通过浏览器保存的数据量小。其目的是要记住您的信息，类似于一个软件应用程序创建的首选项文件。是由一个网站获得，并通过浏览器保存的数据量小。其目的是要记住您的信息，类似于一个软件应用程序创建的首选项文件。是由一个网站获得，并通过浏览器保存的数据量小。其目的是要记住您的信息，类似于一个软件应用程序创建的首选项文件。是由一个网站获得，并通过浏览器保存的数据量小。其目的是要记住您的信息，类似于一个软件应用程序创建的首选项文件。"
    private val text2 =
        "A cookie is a \nsmall amount of data generated \nb\ny a website and saved by your web browser. Its purpose is to remember information about you, similar to a preference file created by a software application. A cookie is a small amount of data generated by a website and saved by your web browser. Its purpose is to remember information about you, similar to a preference file created by a software application. A cookie is a small amount of data generated by a website and saved by your web browser. Its purpose is to remember information about you, similar to a preference file created by a software application."
    private val text3 =
        "Hello World Its purpose is to remember information about you, similar to a preference file created by a software application. Its purpose is to remember information about you, similar to a preference file created by a software application. Its purpose is to remember information about you, similar to a preference file created by a software application. "


    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        //align_text.text = text3
        //normal_text.text = text3
        mix_align_text.text = text3
    }
}
